CUDA_VISIBLE_DEVICES=4,5,6,7 fairseq-train \
    /data/yukangliang/实验/BertKpeEditorWithAdaptor/data-bin-bert-cased-510 \
    --save-dir ../checkpoints_levt_bert_cased_510 \
    --ddp-backend=legacy_ddp \
    --task translation_lev \
    --criterion nat_loss \
    --arch levenshtein_transformer \
    --noise random_delete \
    --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9,0.98)' \
    --lr 0.0005 --lr-scheduler inverse_sqrt \
    --stop-min-lr '1e-09' --warmup-updates 10000 \
    --warmup-init-lr '1e-07' --label-smoothing 0.1 \
    --dropout 0.3 --weight-decay 0.01 \
    --decoder-learned-pos \
    --encoder-learned-pos \
    --apply-bert-init \
    --log-format 'simple' --log-interval 100 \
    --fixed-validation-seed 7 \
    --max-tokens 8000 \
    --max-update 300000 \
    --update-freq 8 \
    --skip-invalid-size-inputs-valid-test \
    --fp16 \
    --no-epoch-checkpoints \